- name: create etcd cert folder for worker hosts
  file:
    state: directory
    path: "{{etcd_install_folder}}/certs"
    mode: u=rwx,g=r,o=
    owner: etcd
    group: etcd
  become: true

- name: copy certificate authority
  copy: 
    src: "{{pki_gen_certs}}/ca.pem"
    dest: "{{etcd_install_folder}}/certs/ca.pem"
  become: true

- name: copy etcd public key to worker hosts
  copy: 
    src: "{{etcd_certs_folder}}/{{inventory_hostname}}.pem"
    dest: "{{etcd_install_folder}}/certs/"
  become: true

- name: copy etcd private key to worker hosts
  copy: 
    src: "{{etcd_certs_folder}}/{{inventory_hostname}}-key.pem"
    dest: "{{etcd_install_folder}}/certs/"
  become: true
