- name: create etcd systemd service
  template:
    src: "templates/etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
  register: etcd_service_create
  become: yes


- name: reload systemd configuration
  systemd:
    daemon_reload: yes
  when: etcd_service_create.changed
  become: yes

- name: activate etcd service on startup
  systemd:
    name: etcd.service
    enabled: yes
  become: yes

- name: stop etcd service
  systemd:
    name: etcd.service
    state: stopped
  become: yes

- name: start etcd service
  systemd:
    name: etcd.service
    state: started
  become: yes

- name: wait for etcd service to be started
  service_facts:
  until: ansible_facts.services['etcd.service'].state == 'running'
  retries: 10
  delay: 2

- name: smoke test to check if the etcd cluster is up (create and delete a key in the cluster)
  shell: | 
    set -e
    key=foo_`date +%s`
    sudo -u etcd {{etcd_install_folder}}/bin/etcdctl --cacert="{{etcd_install_folder}}/certs/etcd-ca.pem" --cert="{{etcd_install_folder}}/certs/{{inventory_hostname}}.pem" --key="{{etcd_install_folder}}/certs/{{inventory_hostname}}-key.pem" put $key bar
    sudo -u etcd {{etcd_install_folder}}/bin/etcdctl --cacert="{{etcd_install_folder}}/certs/etcd-ca.pem" --cert="{{etcd_install_folder}}/certs/{{inventory_hostname}}.pem" --key="{{etcd_install_folder}}/certs/{{inventory_hostname}}-key.pem" del $key
  retries: 10
  delay: 2
  changed_when: False

  

