- name: create etcd certificates folder
  file:
    state: directory
    path: "{{etcd_certs_folder}}"

- name: generate etcd CSR request file
  template: 
    src: "templates/csr.json.j2"
    dest: "{{pki_gen_conf}}/etcd-csr.json"

- name: "generate etcd certificates (one per host)"
  include_tasks: subtask/single-create-cert.yml 
  vars:
    used_signing_ca_prefix: "{{pki_gen_certs}}/ca"
    csr_path: "{{pki_gen_conf}}/etcd-csr.json"
    dest_cert_folder: "{{etcd_certs_folder}}"
    cert_name: "{{item}}"
  loop: "{{workers_in_inventory}}"