- name: generate service account CSR request file
  template: 
    src: "templates/csr.json.j2"
    dest: "{{pki_gen_conf}}/service-account-csr.json"
  vars:
    common_name: "system:service-account"
    organization_unit: kubernetes cluster
    hosts_in_csr: "{{masters_in_inventory}}"

- name: "generate service account certs (authentication between kube controller and kube api servers)"
  include_tasks: subtask/single-create-cert.yml 
  vars:
    used_signing_ca_prefix: "{{pki_gen_certs}}/ca"
    csr_path: "{{pki_gen_conf}}/service-account-csr.json"
    dest_cert_folder: "{{pki_gen_certs}}"
    cert_name: "service-account"
