- name: generate service account CSR request file
  template: 
    src: "templates/csr.json.j2"
    dest: "{{pki_gen_conf}}/kube-controller-manager-csr.json"
  vars:
    common_name: "system:kube-controller-manager"
    organization_unit: kubernetes cluster
    hosts_in_csr: []

- name: "generate kube controller manager account certs (authentication between kube controller and kube api servers)"
  include_tasks: subtask/single-create-cert.yml 
  vars:
    used_signing_ca_prefix: "{{pki_gen_certs}}/ca"
    csr_path: "{{pki_gen_conf}}/kube-controller-manager-csr.json"
    dest_cert_folder: "{{pki_gen_certs}}"
    cert_name: "kube-controller-manager"
