---
- include: prepare-binaries.yml
- name: create Root CA for kubernetes
  include: create-root-ca.yml
  vars:
    certificate_common_name: Kubernetes root CA
    authority_name: ca

- name: create Root CA for etcd cluster
  include: create-root-ca.yml
  vars:
    certificate_common_name: etcd root CA
    authority_name: etcd-ca

- name: create etcd certs
  include: create-etcd-certs.yml

- name: create kube api servers certs
  include: create-kube-apiserver-certs.yml

- name: create service account certs
  include: create-service-account-certs.yml

- name: create controller manager certs
  include: create-kube-controller-manager-certs.yml

- name: create kube-scheduler certs
  include: create-kube-scheduler-certs.yml