- name: "Check if ca exists"
  stat:
      path: "{{pki_gen_certs}}/ca.pem"
  register: "ca_file"

- name: "fail if CA doesnt exist"
  fail: msg="CA doesn't exist, impossible to create a key pair for etcd host {{target_etcd_host}}"
  when: 
    - not ca_file.stat.exists

- name: "Check if certificate exists"
  stat:
    path: "{{etcd_certs_folder}}/{{target_etcd_host}}.pem"
  register: "etcd_cert"

- name: "Check if CA is newer than cert for etcd host {{target_etcd_host}}"
  set_fact:
    ca_is_newer: "{{ca_file.stat.ctime - etcd_cert.stat.ctime > 0}}"
  when:
    - ca_file.stat.exists
    - etcd_cert.stat.exists

- name: "Check if CA needs to (re)create certificates"
  set_fact:
    create_etcd_cert: "{{not etcd_cert.stat.exists or ca_is_newer}}"


-   name: "generate etcd cert for {{target_etcd_host}}"
    shell: |
        set -e
        cd {{etcd_certs_folder}}
        {{pki_gen_bin}}/cfssl gencert -ca {{pki_gen_certs}}/ca.pem -ca-key {{pki_gen_certs}}/ca-key.pem {{pki_gen_conf}}/etcd-csr.json | {{pki_gen_bin}}/cfssljson -bare {{target_etcd_host}}
    args:
        executable: /bin/bash
    when:
        - create_etcd_cert