---
binaries: "/home/vagrant/ansible/binaries"
binaries_predownload: "/vagrant/ansible/binaries_predownload"
binaries_etcd: "{{binaries}}/etcd"
binaries_k8s_server: "{{binaries}}/kube-server"
binaries_k8s_client: "{{binaries}}/kube-node"


pki_gen: "~/ansible/pki"
pki_gen_bin: "~/ansible/pki/bin"
pki_gen_conf: "{{pki_gen}}/conf"
pki_gen_certs: "{{pki_gen}}/certs"
etcd_certs_folder: "{{pki_gen_certs}}/etcd-certs"

pki:
    owner:
        country: "FR"
        location: "Nouvelle Aquitaine"
        organization: "manuelpayet, Inc"
        organization_unit: "mon bureau"
        state: ""
    ca_expiry: 14400h #14400 hours=600 days
    signing_expiry: 14400h #14400 hours=600 days
    renew_ca_if_less_than: +7200h #7200 hours=300 days