- name: create kubernetes api server cert folder for cluster hosts
  file:
    state: directory
    path: "{{kube_certs}}"
    mode: u=rwx,g=r,o=
    owner: etcd
    group: etcd
  become: true

- name: copy certificate authority
  copy: 
    src: "{{pki_gen_certs}}/ca.pem"
    dest: "{{kube_certs}}/ca.pem"
  become: true

- name: copy certificate private key authority
  copy: 
    src: "{{pki_gen_certs}}/ca-key.pem"
    dest: "{{kube_certs}}/ca-key.pem"
  become: true

- name: copy etcd ca authority
  copy: 
    src: "{{pki_gen_certs}}/etcd-ca.pem"
    dest: "{{kube_certs}}/etcd-ca.pem"
  become: true


- name: copy kubernetes public key to master hosts
  copy: 
    src: "{{pki_gen_certs}}/kube-api-server-{{inventory_hostname}}.pem"
    dest: "{{kube_certs}}/kube-api-server-{{inventory_hostname}}.pem"
  become: true

- name: copy kubernetes private key to master hosts
  copy: 
    src: "{{pki_gen_certs}}/kube-api-server-{{inventory_hostname}}-key.pem"
    dest: "{{kube_certs}}/kube-api-server-{{inventory_hostname}}-key.pem"
  become: true

- name: copy service account public key to master hosts
  copy: 
    src: "{{pki_gen_certs}}/service-account.pem"
    dest: "{{kube_certs}}/service-account.pem"
  become: true

- name: copy kube-controller-manager public key to master hosts
  copy: 
    src: "{{pki_gen_certs}}/kube-controller-manager.pem"
    dest: "{{kube_certs}}/kube-controller-manager.pem"
  become: true


- name: copy kube-controller-manager private key to master hosts
  copy: 
    src: "{{pki_gen_certs}}/kube-controller-manager-key.pem"
    dest: "{{kube_certs}}/kube-controller-manager-key.pem"
  become: true
  