- name: install kube-apiserver
  unarchive:
      src: "{{binaries_k8s_server}}/kubernetes-server-linux-amd64.tar.gz" 
      copy: true
      dest: "{{kube_install}}/bin" 
      owner: kubernetes 
      extra_opts:  
        - --strip=3
        - --wildcards
        - '*/kube-apiserver'
  become: yes

- name: create kubernete API server systemd service
  template:
    src: "templates/kube-api-server.service.j2"
    dest: "/etc/systemd/system/kube-api-server.service"
  register: kube_api_server_service_create
  become: yes


- name: reload systemd configuration
  systemd:
    daemon_reload: yes
  when: kube_api_server_service_create.changed
  become: yes

- name: activate Kubernetes API Server service on startup
  systemd:
    name: kube-api-server.service
    enabled: yes
  become: yes

- name: stop Kubernetes API Server service
  systemd:
    name:  kube-api-server.service
    state: stopped
  become: yes

- name: start Kubernetes API Server service
  systemd:
    name: kube-api-server.service
    state: started
  become: yes

- name: wait for kube-api-server service to be started
  service_facts:
  until: ansible_facts.services['kube-api-server.service'].state == 'running'
  retries: 10
  delay: 2

