- name: install kube-scheduler
  unarchive:
      src: "{{binaries_k8s_server}}/kubernetes-server-linux-amd64.tar.gz" 
      copy: true
      dest: "{{kube_install}}/bin" 
      owner: kubernetes 
      extra_opts:  
        - --strip=3
        - --wildcards
        - '*/kube-scheduler'
  become: yes



- name: copy kubernetes scheduler kubeconfig
  template:
    src: "templates/kubeconfig.yml.j2"
    dest: "{{kube_install}}/etc/kube-scheduler-kubeconfig.yml"
  vars:
    client_certificate: "{{kube_certs}}/kube-scheduler.pem"
    client_key: "{{kube_certs}}/kube-scheduler-key.pem"
  register: kube_scheduler_service_create
  become: yes


- name: copy kubernetes scheduler config
  template:
    src: "templates/kube-scheduler.yml.j2"
    dest: "{{kube_install}}/etc/kube-scheduler.yml"
  vars:
    kube_config: "{{kube_install}}/etc/kube-scheduler-kubeconfig.yml"
  register: kube_scheduler_service_create
  become: yes

- name: create kubernetes controller manager systemd service
  template:
    src: "templates/kube-scheduler.service.j2"
    dest: "/etc/systemd/system/kube-scheduler.service"
  register: kube_scheduler_service_create
  become: yes


- name: reload systemd configuration
  systemd:
    daemon_reload: yes
  when: kube_scheduler_service_create.changed
  become: yes

- name: activate kubernetes scheduler service on startup
  systemd:
    name: kube-scheduler.service
    enabled: yes
  become: yes

- name: stop kube-scheduler service
  systemd:
    name: kube-scheduler.service
    state: stopped
  become: yes

- name: start kube-scheduler service
  systemd:
    name: kube-scheduler.service
    state: started
  become: yes

- name: wait for kube-scheduler service to be started
  service_facts:
  until: ansible_facts.services['kube-scheduler.service'].state == 'running'
  retries: 10
  delay: 2

